// <auto-generated />
namespace WeekendTask_30._06._2019_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class some : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(some));
        
        string IMigrationMetadata.Id
        {
            get { return "201906301550512_some"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
